# Automatic dependency updates

version: 2
updates:
  # Enable version updates ui
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ui (npm)"
    labels:
      - "dependencies"
      - "UI"

  # Enable version updates api
  - package-ecosystem: "gomod"
    directory: "/api"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "api (gomod)"
    labels:
      - "dependencies"
      - "API"
