version: "3"

services:
  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=photoview
      - MYSQL_USER=photoview
      - MYSQL_PASSWORD=photo-secret
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    volumes:
      - db_data:/var/lib/mysql

  photoview:
    build:
      context: "."
      args:
        - GRAPHQL_ENDPOINT=http://localhost:8000/api/graphql

    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db

    environment:
      - MYSQL_URL=photoview:photo-secret@tcp(db)/photoview
      - PHOTO_CACHE=/app/cache
      # Change This: The publicly exposed url for the api
      # For example if the server is available from the domain example.com,
      # change this value to http://example.com/api
      - API_ENDPOINT=http://localhost:80/
      - PUBLIC_ENDPOINT=http://localhost:8000/

    volumes:
      # Change This: Link photo paths from the host machine
      # Change this to the directory where your photos are located on your server.
      # If the photos are located at `/home/user/photos`, then change this value
      # to the following: `/home/user/photos:/photos:ro`.
      # You can mount multiple paths, if your photos are spread across multiple directories.
      - ./photos_path:/photos:ro
      - api_cache:/app/cache

volumes:
  db_data:
  api_cache:
