services:
  - type: web
    name: photoview
    env: docker
    plan: starter
    repo: https://github.com/marvimarv/photoview
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PHOTOVIEW_DATABASE_DRIVER
        value: sqlite
      - key: PHOTOVIEW_DATABASE_DSN
        value: /home/photoview/database.db
    volumes:
      - path: /home/photoview
